.TH ICALC 1 2015-01-16
.SH NAME
.B icalc
\- terrible interactive calculator 
.
.SH SYNOPSIS
.B icalc
.
.SH OPTIONS
None, so far.
.
.SH EXIT STATUS
.B icalc
will always exit with 0.
.
.SH NOTES
Don't use this.
I wrote it to learn C, Make and troff.
It's terrible and you almost certainly want
.B bc(1)
instead.
.
.SH BUGS
There is no
.B make install
currently written.
.
.SH AUTHOR
.B icalc
was written by Alex Jordan <alex@strugee.net>.
.
.SH SEE ALSO
.B bc(1)
